// AUTO-GENERATED by scripts/photos.mjs — do not edit by hand.
// Regenerate with: pnpm photos
// Series order = display order (footer words / hover panel numbering).

export interface Photo {
  thumb: string
  full: string
  w: number // thumb pixel size (aspect = w/h, true for the shot)
  h: number
}

export interface Series {
  slug: string
  name: string
  category: Category
  year: number
  photos: Photo[]
}

export type Category = "street" | "scenery" | "live"

export const CATEGORIES: { slug: Category; label: string }[] = [
  { slug: "street", label: "STREET" },
  { slug: "scenery", label: "SCENERY" },
  { slug: "live", label: "LIVE" },
]

export const SERIES: Series[] = [
  { slug: "beijing", name: "BEIJING", category: "street", year: 2025, photos: [
    { thumb: "/photos/beijing-01-t-0e5774c4.webp", full: "/photos/beijing-01-f-c2439672.webp", w: 720, h: 480 },
    { thumb: "/photos/beijing-02-t-00d87901.webp", full: "/photos/beijing-02-f-7c0244ce.webp", w: 720, h: 316 },
    { thumb: "/photos/beijing-03-t-71c4c18f.webp", full: "/photos/beijing-03-f-2555d475.webp", w: 720, h: 480 },
    { thumb: "/photos/beijing-04-t-60acf4d9.webp", full: "/photos/beijing-04-f-62ca3330.webp", w: 720, h: 480 },
    { thumb: "/photos/beijing-05-t-da598712.webp", full: "/photos/beijing-05-f-995f2d93.webp", w: 720, h: 523 },
    { thumb: "/photos/beijing-06-t-7363bae9.webp", full: "/photos/beijing-06-f-c163d661.webp", w: 720, h: 480 },
    { thumb: "/photos/beijing-07-t-df3cf4ac.webp", full: "/photos/beijing-07-f-3d7fa83e.webp", w: 720, h: 480 },
    { thumb: "/photos/beijing-08-t-f6407c94.webp", full: "/photos/beijing-08-f-0a28466d.webp", w: 720, h: 1080 },
    { thumb: "/photos/beijing-09-t-b8e97c88.webp", full: "/photos/beijing-09-f-a11c5d2a.webp", w: 720, h: 435 },
    { thumb: "/photos/beijing-10-t-000a3108.webp", full: "/photos/beijing-10-f-95ca5856.webp", w: 720, h: 1080 },
    { thumb: "/photos/beijing-11-t-fb2aab1f.webp", full: "/photos/beijing-11-f-166ca6c4.webp", w: 720, h: 1048 },
    { thumb: "/photos/beijing-12-t-5ff9b63e.webp", full: "/photos/beijing-12-f-2c25ea68.webp", w: 720, h: 480 },
    { thumb: "/photos/beijing-13-t-a49c7168.webp", full: "/photos/beijing-13-f-dc73f2ea.webp", w: 720, h: 340 },
  ] },
  { slug: "shanghai", name: "SHANGHAI", category: "street", year: 2026, photos: [
    { thumb: "/photos/shanghai-01-t-a30623e5.webp", full: "/photos/shanghai-01-f-bb28655f.webp", w: 720, h: 1115 },
    { thumb: "/photos/shanghai-02-t-1240a39e.webp", full: "/photos/shanghai-02-f-19c93f96.webp", w: 720, h: 963 },
    { thumb: "/photos/shanghai-03-t-7966dae8.webp", full: "/photos/shanghai-03-f-bb0b12ce.webp", w: 720, h: 456 },
    { thumb: "/photos/shanghai-04-t-9ad9584b.webp", full: "/photos/shanghai-04-f-dff94cd2.webp", w: 720, h: 1080 },
    { thumb: "/photos/shanghai-05-t-b7471533.webp", full: "/photos/shanghai-05-f-5a5a4fce.webp", w: 720, h: 1080 },
    { thumb: "/photos/shanghai-06-t-19c26633.webp", full: "/photos/shanghai-06-f-fef4416e.webp", w: 720, h: 572 },
    { thumb: "/photos/shanghai-07-t-c9b31b26.webp", full: "/photos/shanghai-07-f-8a1ec0b7.webp", w: 720, h: 1080 },
    { thumb: "/photos/shanghai-08-t-76b4e08b.webp", full: "/photos/shanghai-08-f-1ecd75fa.webp", w: 720, h: 457 },
    { thumb: "/photos/shanghai-09-t-351efc01.webp", full: "/photos/shanghai-09-f-a48857fb.webp", w: 720, h: 1111 },
    { thumb: "/photos/shanghai-10-t-e1626431.webp", full: "/photos/shanghai-10-f-e4b90430.webp", w: 720, h: 1080 },
    { thumb: "/photos/shanghai-11-t-14e77193.webp", full: "/photos/shanghai-11-f-4b582170.webp", w: 720, h: 1080 },
    { thumb: "/photos/shanghai-12-t-260a438f.webp", full: "/photos/shanghai-12-f-e513e506.webp", w: 720, h: 1081 },
    { thumb: "/photos/shanghai-13-t-ba112590.webp", full: "/photos/shanghai-13-f-972ca57a.webp", w: 720, h: 1083 },
    { thumb: "/photos/shanghai-14-t-04482bce.webp", full: "/photos/shanghai-14-f-09fba68c.webp", w: 720, h: 445 },
    { thumb: "/photos/shanghai-15-t-a22e5974.webp", full: "/photos/shanghai-15-f-f4e67096.webp", w: 720, h: 307 },
    { thumb: "/photos/shanghai-16-t-acf570d3.webp", full: "/photos/shanghai-16-f-41bdd959.webp", w: 720, h: 380 },
    { thumb: "/photos/shanghai-17-t-0bf8ff5b.webp", full: "/photos/shanghai-17-f-df65a771.webp", w: 720, h: 465 },
    { thumb: "/photos/shanghai-18-t-89225717.webp", full: "/photos/shanghai-18-f-c59e9271.webp", w: 720, h: 445 },
    { thumb: "/photos/shanghai-19-t-1be22d5e.webp", full: "/photos/shanghai-19-f-17e87922.webp", w: 720, h: 480 },
  ] },
  { slug: "sichuan", name: "SICHUAN", category: "scenery", year: 2026, photos: [
    { thumb: "/photos/sichuan-01-t-4ba63113.webp", full: "/photos/sichuan-01-f-794450ff.webp", w: 720, h: 1182 },
    { thumb: "/photos/sichuan-02-t-66704a83.webp", full: "/photos/sichuan-02-f-4a1dc8ca.webp", w: 720, h: 406 },
    { thumb: "/photos/sichuan-03-t-28754d70.webp", full: "/photos/sichuan-03-f-9816e030.webp", w: 720, h: 480 },
    { thumb: "/photos/sichuan-04-t-7c355fec.webp", full: "/photos/sichuan-04-f-bacadffd.webp", w: 720, h: 396 },
    { thumb: "/photos/sichuan-05-t-cea9ad60.webp", full: "/photos/sichuan-05-f-926d3cce.webp", w: 720, h: 414 },
    { thumb: "/photos/sichuan-06-t-66a8a751.webp", full: "/photos/sichuan-06-f-83b2e320.webp", w: 720, h: 447 },
    { thumb: "/photos/sichuan-07-t-26f0799e.webp", full: "/photos/sichuan-07-f-4c1a95a9.webp", w: 720, h: 1080 },
    { thumb: "/photos/sichuan-08-t-8bf3582a.webp", full: "/photos/sichuan-08-f-32148acd.webp", w: 720, h: 382 },
    { thumb: "/photos/sichuan-09-t-9f418a1f.webp", full: "/photos/sichuan-09-f-8c0c7ee2.webp", w: 720, h: 1080 },
  ] },
  { slug: "yunnan", name: "YUNNAN", category: "scenery", year: 2026, photos: [
    { thumb: "/photos/yunnan-01-t-9269f444.webp", full: "/photos/yunnan-01-f-81f01a78.webp", w: 720, h: 480 },
    { thumb: "/photos/yunnan-02-t-bbe2ce8c.webp", full: "/photos/yunnan-02-f-18dc7644.webp", w: 720, h: 480 },
    { thumb: "/photos/yunnan-03-t-0dc9c842.webp", full: "/photos/yunnan-03-f-0d2b8e19.webp", w: 720, h: 480 },
    { thumb: "/photos/yunnan-04-t-b7009863.webp", full: "/photos/yunnan-04-f-7f1394c2.webp", w: 720, h: 445 },
    { thumb: "/photos/yunnan-05-t-1827f428.webp", full: "/photos/yunnan-05-f-9c038e9c.webp", w: 720, h: 400 },
    { thumb: "/photos/yunnan-06-t-438cf66f.webp", full: "/photos/yunnan-06-f-789f45b4.webp", w: 720, h: 1049 },
    { thumb: "/photos/yunnan-07-t-9c7f38a9.webp", full: "/photos/yunnan-07-f-c98a847e.webp", w: 720, h: 1080 },
  ] },
  { slug: "david-tao", name: "DAVID TAO", category: "live", year: 2026, photos: [
    { thumb: "/photos/david-tao-01-t-3ca6633a.webp", full: "/photos/david-tao-01-f-ccd362f1.webp", w: 720, h: 439 },
    { thumb: "/photos/david-tao-02-t-552e902c.webp", full: "/photos/david-tao-02-f-28e46262.webp", w: 720, h: 425 },
    { thumb: "/photos/david-tao-03-t-e4018f7e.webp", full: "/photos/david-tao-03-f-34e00f54.webp", w: 720, h: 467 },
    { thumb: "/photos/david-tao-04-t-c3d3188b.webp", full: "/photos/david-tao-04-f-e8900b2d.webp", w: 720, h: 424 },
    { thumb: "/photos/david-tao-05-t-e848cce8.webp", full: "/photos/david-tao-05-f-255619c1.webp", w: 720, h: 368 },
    { thumb: "/photos/david-tao-06-t-a6056fa7.webp", full: "/photos/david-tao-06-f-54bf153e.webp", w: 720, h: 405 },
    { thumb: "/photos/david-tao-07-t-d2506080.webp", full: "/photos/david-tao-07-f-38e6e5ee.webp", w: 720, h: 430 },
    { thumb: "/photos/david-tao-08-t-e077b259.webp", full: "/photos/david-tao-08-f-dc65ccdf.webp", w: 720, h: 435 },
    { thumb: "/photos/david-tao-09-t-92d088d7.webp", full: "/photos/david-tao-09-f-b219e76e.webp", w: 720, h: 450 },
    { thumb: "/photos/david-tao-10-t-db3a8e7d.webp", full: "/photos/david-tao-10-f-8b8bd31d.webp", w: 720, h: 350 },
    { thumb: "/photos/david-tao-11-t-c02a5ff4.webp", full: "/photos/david-tao-11-f-6e9228c0.webp", w: 720, h: 406 },
    { thumb: "/photos/david-tao-12-t-14e188cc.webp", full: "/photos/david-tao-12-f-7e2c19b5.webp", w: 720, h: 368 },
    { thumb: "/photos/david-tao-13-t-b5fa4cff.webp", full: "/photos/david-tao-13-f-681f1ee8.webp", w: 720, h: 379 },
    { thumb: "/photos/david-tao-14-t-bd3786bb.webp", full: "/photos/david-tao-14-f-421c88f4.webp", w: 720, h: 388 },
    { thumb: "/photos/david-tao-15-t-9fed5821.webp", full: "/photos/david-tao-15-f-6913fc1f.webp", w: 720, h: 452 },
    { thumb: "/photos/david-tao-16-t-922dce46.webp", full: "/photos/david-tao-16-f-b2819e67.webp", w: 720, h: 1067 },
  ] },
]

export const AVATAR: { src: string; w: number; h: number } = { src: "/photos/portrait-1ace561b.webp", w: 900, h: 1311 }
