// AUTO-GENERATED by scripts/photos.mjs — do not edit by hand.
// Regenerate with: pnpm photos
// Series order = display order (footer words / hover panel numbering).

export interface Photo {
  thumb: string
  full: string
  w: number // thumb pixel size (aspect = w/h, true for the shot)
  h: number
}

export interface Series {
  slug: string
  name: string
  category: Category
  year: number
  photos: Photo[]
}

export type Category = "street" | "scenery" | "live"

export const CATEGORIES: { slug: Category; label: string }[] = [
  { slug: "street", label: "STREET" },
  { slug: "scenery", label: "SCENERY" },
  { slug: "live", label: "LIVE" },
]

export const SERIES: Series[] = [
  { slug: "beijing", name: "BEIJING", category: "street", year: 2025, photos: [
    { thumb: "/photos/beijing-01-t-d1ad9f7a.webp", full: "/photos/beijing-01-f-94f2196a.webp", w: 960, h: 640 },
    { thumb: "/photos/beijing-02-t-e09e568e.webp", full: "/photos/beijing-02-f-f250b608.webp", w: 960, h: 422 },
    { thumb: "/photos/beijing-03-t-7e8c8643.webp", full: "/photos/beijing-03-f-644ecaed.webp", w: 960, h: 640 },
    { thumb: "/photos/beijing-04-t-4ef5395f.webp", full: "/photos/beijing-04-f-649ee700.webp", w: 960, h: 640 },
    { thumb: "/photos/beijing-05-t-4d24dd13.webp", full: "/photos/beijing-05-f-ec790049.webp", w: 960, h: 697 },
    { thumb: "/photos/beijing-06-t-244ada15.webp", full: "/photos/beijing-06-f-99c14dd8.webp", w: 960, h: 640 },
    { thumb: "/photos/beijing-07-t-e30099e5.webp", full: "/photos/beijing-07-f-55c9ab3a.webp", w: 960, h: 640 },
    { thumb: "/photos/beijing-08-t-ec04a0d6.webp", full: "/photos/beijing-08-f-4db17a4f.webp", w: 960, h: 1440 },
    { thumb: "/photos/beijing-09-t-51e0c3a1.webp", full: "/photos/beijing-09-f-1e01327c.webp", w: 960, h: 579 },
    { thumb: "/photos/beijing-10-t-621b16cf.webp", full: "/photos/beijing-10-f-38133375.webp", w: 960, h: 1440 },
    { thumb: "/photos/beijing-11-t-966d321c.webp", full: "/photos/beijing-11-f-67919cf4.webp", w: 960, h: 1397 },
    { thumb: "/photos/beijing-12-t-2d39cb03.webp", full: "/photos/beijing-12-f-2a1ce32c.webp", w: 960, h: 640 },
    { thumb: "/photos/beijing-13-t-cbeef345.webp", full: "/photos/beijing-13-f-6ac8e74d.webp", w: 960, h: 453 },
  ] },
  { slug: "shanghai", name: "SHANGHAI", category: "street", year: 2026, photos: [
    { thumb: "/photos/shanghai-01-t-73328efa.webp", full: "/photos/shanghai-01-f-95dfd5e4.webp", w: 960, h: 1487 },
    { thumb: "/photos/shanghai-02-t-99f601ac.webp", full: "/photos/shanghai-02-f-18b0f29e.webp", w: 960, h: 1283 },
    { thumb: "/photos/shanghai-03-t-3ec6358e.webp", full: "/photos/shanghai-03-f-337904a2.webp", w: 960, h: 608 },
    { thumb: "/photos/shanghai-04-t-539ee494.webp", full: "/photos/shanghai-04-f-78c8dd37.webp", w: 960, h: 1440 },
    { thumb: "/photos/shanghai-05-t-b22c43fa.webp", full: "/photos/shanghai-05-f-b1b817ae.webp", w: 960, h: 1440 },
    { thumb: "/photos/shanghai-06-t-dd513a62.webp", full: "/photos/shanghai-06-f-6e0ac048.webp", w: 960, h: 763 },
    { thumb: "/photos/shanghai-07-t-00323053.webp", full: "/photos/shanghai-07-f-517a731f.webp", w: 960, h: 1440 },
    { thumb: "/photos/shanghai-08-t-aa444a5a.webp", full: "/photos/shanghai-08-f-671d6e8f.webp", w: 960, h: 609 },
    { thumb: "/photos/shanghai-09-t-d14de365.webp", full: "/photos/shanghai-09-f-de15a75b.webp", w: 960, h: 1482 },
    { thumb: "/photos/shanghai-10-t-4463c3ab.webp", full: "/photos/shanghai-10-f-8f69a232.webp", w: 960, h: 1440 },
    { thumb: "/photos/shanghai-11-t-4a5ed7c3.webp", full: "/photos/shanghai-11-f-5661a03f.webp", w: 960, h: 1440 },
    { thumb: "/photos/shanghai-12-t-bc1075c0.webp", full: "/photos/shanghai-12-f-126b5658.webp", w: 960, h: 1441 },
    { thumb: "/photos/shanghai-13-t-b8d4dd4e.webp", full: "/photos/shanghai-13-f-ff85c1f9.webp", w: 960, h: 1444 },
    { thumb: "/photos/shanghai-14-t-24265aab.webp", full: "/photos/shanghai-14-f-ae7f0d08.webp", w: 960, h: 594 },
    { thumb: "/photos/shanghai-15-t-dbd47bd9.webp", full: "/photos/shanghai-15-f-3ee00c5f.webp", w: 960, h: 409 },
    { thumb: "/photos/shanghai-16-t-9e362222.webp", full: "/photos/shanghai-16-f-0d793192.webp", w: 960, h: 506 },
    { thumb: "/photos/shanghai-17-t-3d403c2b.webp", full: "/photos/shanghai-17-f-0c85aba2.webp", w: 960, h: 620 },
    { thumb: "/photos/shanghai-18-t-56ede13a.webp", full: "/photos/shanghai-18-f-22b44109.webp", w: 960, h: 594 },
    { thumb: "/photos/shanghai-19-t-0e1fa256.webp", full: "/photos/shanghai-19-f-92b501d5.webp", w: 960, h: 640 },
  ] },
  { slug: "sichuan", name: "SICHUAN", category: "scenery", year: 2026, photos: [
    { thumb: "/photos/sichuan-01-t-496f81f3.webp", full: "/photos/sichuan-01-f-bedea968.webp", w: 960, h: 1576 },
    { thumb: "/photos/sichuan-02-t-112e97dc.webp", full: "/photos/sichuan-02-f-a3bb3a0b.webp", w: 960, h: 542 },
    { thumb: "/photos/sichuan-03-t-c943b544.webp", full: "/photos/sichuan-03-f-77816123.webp", w: 960, h: 640 },
    { thumb: "/photos/sichuan-04-t-a2f7aadc.webp", full: "/photos/sichuan-04-f-fa1745d4.webp", w: 960, h: 529 },
    { thumb: "/photos/sichuan-05-t-2855a534.webp", full: "/photos/sichuan-05-f-fce257df.webp", w: 960, h: 553 },
    { thumb: "/photos/sichuan-06-t-f32d2c4e.webp", full: "/photos/sichuan-06-f-e497e9c4.webp", w: 960, h: 597 },
    { thumb: "/photos/sichuan-07-t-49bd5a78.webp", full: "/photos/sichuan-07-f-ccdd707c.webp", w: 960, h: 1440 },
    { thumb: "/photos/sichuan-08-t-bf68c20c.webp", full: "/photos/sichuan-08-f-384105fe.webp", w: 960, h: 509 },
    { thumb: "/photos/sichuan-09-t-4f6ad36e.webp", full: "/photos/sichuan-09-f-4c84b865.webp", w: 960, h: 1440 },
  ] },
  { slug: "yunnan", name: "YUNNAN", category: "scenery", year: 2026, photos: [
    { thumb: "/photos/yunnan-01-t-2436b128.webp", full: "/photos/yunnan-01-f-ddce3ee7.webp", w: 960, h: 640 },
    { thumb: "/photos/yunnan-02-t-e3f2cf9a.webp", full: "/photos/yunnan-02-f-87854989.webp", w: 960, h: 640 },
    { thumb: "/photos/yunnan-03-t-6789b031.webp", full: "/photos/yunnan-03-f-308260d8.webp", w: 960, h: 640 },
    { thumb: "/photos/yunnan-04-t-c6814a9d.webp", full: "/photos/yunnan-04-f-95e88208.webp", w: 960, h: 593 },
    { thumb: "/photos/yunnan-05-t-40dc3b51.webp", full: "/photos/yunnan-05-f-67484be6.webp", w: 960, h: 533 },
    { thumb: "/photos/yunnan-06-t-3f65f6ee.webp", full: "/photos/yunnan-06-f-84680283.webp", w: 960, h: 1398 },
    { thumb: "/photos/yunnan-07-t-d1222187.webp", full: "/photos/yunnan-07-f-c589490e.webp", w: 960, h: 1440 },
  ] },
  { slug: "david-tao", name: "DAVID TAO", category: "live", year: 2026, photos: [
    { thumb: "/photos/david-tao-01-t-8944ccac.webp", full: "/photos/david-tao-01-f-12ddde5f.webp", w: 960, h: 585 },
    { thumb: "/photos/david-tao-02-t-988e8f9c.webp", full: "/photos/david-tao-02-f-deb6709b.webp", w: 960, h: 567 },
    { thumb: "/photos/david-tao-03-t-d2ece220.webp", full: "/photos/david-tao-03-f-d546f460.webp", w: 960, h: 623 },
    { thumb: "/photos/david-tao-04-t-7005a27e.webp", full: "/photos/david-tao-04-f-bcc91c21.webp", w: 960, h: 566 },
    { thumb: "/photos/david-tao-05-t-7b4a5c8d.webp", full: "/photos/david-tao-05-f-ddf3bc11.webp", w: 960, h: 490 },
    { thumb: "/photos/david-tao-06-t-51c3dabb.webp", full: "/photos/david-tao-06-f-ec78d9fb.webp", w: 960, h: 540 },
    { thumb: "/photos/david-tao-07-t-28b2e133.webp", full: "/photos/david-tao-07-f-e7de59d7.webp", w: 960, h: 574 },
    { thumb: "/photos/david-tao-08-t-bb0e7d53.webp", full: "/photos/david-tao-08-f-f1d393ab.webp", w: 960, h: 581 },
    { thumb: "/photos/david-tao-09-t-f36b9398.webp", full: "/photos/david-tao-09-f-15472448.webp", w: 960, h: 601 },
    { thumb: "/photos/david-tao-10-t-d4fd527d.webp", full: "/photos/david-tao-10-f-531c32c1.webp", w: 960, h: 467 },
    { thumb: "/photos/david-tao-11-t-c6ec9af4.webp", full: "/photos/david-tao-11-f-286ba057.webp", w: 960, h: 541 },
    { thumb: "/photos/david-tao-12-t-bce6690b.webp", full: "/photos/david-tao-12-f-aa9c0aa8.webp", w: 960, h: 491 },
    { thumb: "/photos/david-tao-13-t-2d33523b.webp", full: "/photos/david-tao-13-f-7a5a9de1.webp", w: 960, h: 506 },
    { thumb: "/photos/david-tao-14-t-91427829.webp", full: "/photos/david-tao-14-f-ec910bd3.webp", w: 960, h: 517 },
    { thumb: "/photos/david-tao-15-t-cef7b274.webp", full: "/photos/david-tao-15-f-482d36b6.webp", w: 960, h: 604 },
    { thumb: "/photos/david-tao-16-t-83aaa897.webp", full: "/photos/david-tao-16-f-86f10387.webp", w: 960, h: 1423 },
  ] },
]

export const AVATAR: { src: string; w: number; h: number } = { src: "/photos/portrait-05a3bed3.webp", w: 1073, h: 1563 }
