// Shared photo-wall model.
// The single source of truth is src/photo-manifest.ts (generated by
// scripts/photos.mjs from photo/). Everything here is derived, typed glue.

import {
  SERIES,
  CATEGORIES,
  AVATAR,
  type Series,
  type Category,
  type Photo,
} from "./photo-manifest"

export type { Series, Category, Photo }
export { SERIES, CATEGORIES, AVATAR }

export type CatFilter = Category | "all"

/** One cell on the wall: a concrete photo + the series it belongs to. */
export interface WallPhoto {
  series: Series
  /** 0-based index inside the series (deep link uses index + 1) */
  index: number
  photo: Photo
}

/** Every photo of every series, series order first. */
export const WALL: WallPhoto[] = SERIES.flatMap((series) =>
  series.photos.map((photo, index) => ({ series, index, photo })),
)

export function seriesBySlug(slug: string): Series | null {
  return SERIES.find((s) => s.slug === slug) ?? null
}

export function wallForCat(cat: CatFilter): WallPhoto[] {
  return cat === "all" ? WALL : WALL.filter((w) => w.series.category === cat)
}

/** Series order number 01–05 for hover panel / list strip. */
export function seriesNumber(series: Series): number {
  return SERIES.findIndex((s) => s.slug === series.slug) + 1
}

// Deterministic PRNG (mulberry32) — the wall shuffle must be stable between
// reloads so a visitor scrolling back up sees photos in the same places.
export function shuffled<T>(arr: T[], seed: number): T[] {
  const a = arr.slice()
  let t = seed
  const rnd = () => {
    t += 0x6d2b79f5
    let r = Math.imul(t ^ (t >>> 15), 1 | t)
    r ^= r + Math.imul(r ^ (r >>> 7), 61 | r)
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296
  }
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

// Per-column vertical stagger (px) — organic "not on the same baseline" feel
export const COL_OFFSETS = [0, 18, -14, 9]

// Cover for the list strip: first photo of the series (G-table default).
export const coverOf = (series: Series): Photo => series.photos[0]
